const blogApi =[
    {
        id: 1,
        link: 'mi-primer-hola-mundo',
        image: 'https://cdn.luifereduardoo.com/img/blog/hola_mundo.webp',
        creditosImage: ['https://cdn.luifereduardoo.com/img/blog/hola_mundo.webp', 'aquí'],
        title: 'Mi primer "Hola mundo"',
        date: 'Saturday, 31 December 2022 19:40:04',
        content: 'Cuando se le pregunta a cualquier persona cómo fue que descubrió que eso a lo cual se está dedicando es lo que le apasiona y le da sentido a su vida, muchas veces te responden con historias completamente diferentes. Algunas personas pueden haber descubierto su propósito en la vida en una clase en la escuela, u otra en cambio lo logro descubrir al empezar a practicar un nuevo deporte. Pero a pesar de lo diferentes que pueden ser las historias, siempre hay algo en común cuando realmente descubre tu propósito: es algo de esa profesión que al minuto cuando lo vistes te dejo sin palabras y con una emoción no antes experimentada. Y eso me pasó a mí. Recuerdo que la primera vez que yo pude tener acceso a una laptop fue cuando tenía 4 años, pero esta primera interacción no me hizo descubrir lo que me gusta, sino que me hizo ser otro consumidor más de tecnología. Pero, sin embargo, sí podría decir que esta interacción hizo que me despertara en mí una gran curiosidad por todo lo relacionado con la tecnología. Tanto así que con tan solo tener 5 años ya lograba tener un manejo exquisito de una laptop (Sin saber leer ni escribir). La verdad es que ni las personas que en ese momento me veían con mi corta edad manipulando una laptop, entendían cómo podía hacer todo eso. Era como si yo estuviera hecho para eso. Regresando a lo que comentaba en el primer párrafo, lo que me hizo darme cuenta de que el mundo de la tecnología es a lo que me quiero y estoy dedicando, no fue esa primera interacción. De hecho, que en esos años cuando era niño soñaba con ser médico y en ningún momento por la cabeza se me ocurriría dedicarme a el mundo tecnológico. Eso ocurrió cuando tenía 13 años, el día que logre escribir en pantalla mi primer “¡Hola mundo!”. Sería complicado explicar cómo me sentía ese día, mi emoción por el nuevo mundo que estaba descubriendo. Pero desde el preciso momento en que logre imprimir ese mensaje, mi vida cambió y logre entender cuál es mi propósito en la vida, que luego de unos años se reforzó cada vez que experimentaba en este mundo. Me impresiona cómo un simple mensaje hecho con una línea de código (que todo programador alguna vez en su vida lo ha escrito) te puede mostrar tu pasión en la vida. No sé si dentro de unos 20 años me siga dedicando a esto, pero lo único que sé, es que estoy haciendo lo que me hace feliz y me apasiona.',
        tags: ['historias', 'personal', 'programacion']
    },
    {
        id: 2,
        link: 'masjestuosidad-del-vuelo',
        image: 'https://cdn.pixabay.com/photo/2023/03/29/12/43/birdphotography-7885377_1280.jpg',
        title: 'La majestuosidad del vuelo: retrato de un ave en plena libertad',
        date: 'Friday, 4 Aprir 2023 19:40:04',
        content: 'El vuelo de las aves es uno de los espectáculos más fascinantes que nos ofrece la naturaleza. La sensación de libertad y de conexión con el mundo que experimentan estos animales al surcar los cielos es algo que nos deja sin aliento. En esta imagen, podemos ver a un ave en pleno vuelo, con sus alas abiertas y extendidas al máximo. La belleza de su plumaje y la elegancia de sus movimientos son simplemente impresionantes. Pero más allá de su apariencia física, lo que realmente nos llama la atención de esta ave es la sensación de libertad que transmite. Al observarla, es fácil imaginar lo que debe sentir al volar a través de los vientos, sin ninguna restricción ni obstáculo que le impida avanzar. Esta imagen nos recuerda la importancia de preservar la naturaleza y proteger a estas criaturas maravillosas. Es nuestro deber como seres humanos asegurarnos de que las aves y otras especies puedan seguir disfrutando de su hábitat natural y vivir en armonía con el medio ambiente. En resumen, esta imagen es una celebración de la majestuosidad del vuelo de las aves y un recordatorio de la importancia de preservar la vida salvaje y su hábitat natural.',
        tags: ['historias']
    },
    {
        id: 3,
        link: 'belleza-fotograficas',
        image: 'https://cdn.pixabay.com/photo/2016/01/09/18/27/camera-1130731_1280.jpg',
        title: 'La belleza atemporal de las fotografías: capturando momentos únicos y especiales',
        date: 'Thuesday, 3 Aprir 2023 19:40:04',
        content: 'Las fotografías son una de las formas más hermosas de capturar la belleza del mundo que nos rodea. A través de la lente de una cámara, podemos inmortalizar momentos únicos y especiales que de otra manera se perderían en el tiempo. Hay algo mágico en el proceso de tomar fotografías. Desde la elección del encuadre perfecto hasta la captura del momento exacto, cada paso es un desafío creativo que nos permite explorar nuestra propia visión del mundo y plasmarla en una imagen. Pero lo más hermoso de tomar fotografías es que nos permite detener el tiempo. Cuando miramos una foto, no solo estamos viendo una imagen, sino que también estamos reviviendo un momento del pasado, sintiendo las mismas emociones y sensaciones que experimentamos en ese instante. Las fotografías nos permiten conectarnos con nuestro entorno de una manera más profunda y significativa. Al tomar una foto, estamos capturando no solo la imagen sino también la esencia del momento, la luz, los colores, los sonidos y los olores que lo rodean. En definitiva, tomar fotografías es una forma de arte que nos permite capturar la belleza del mundo y crear recuerdos inolvidables. Ya sea con una cámara profesional o con nuestro teléfono móvil, siempre tendremos la oportunidad de capturar esos momentos únicos y especiales que hacen que la vida valga la pena.',
        tags: ['historias', 'fotografia']
    },
    {
        id: 4,
        link: 'elefantes-criaturas-majestuosas',
        image: 'https://cdn.pixabay.com/photo/2016/11/14/04/45/elephant-1822636_1280.jpg',
        title: 'Mi primer "Hola mundo',
        date: 'Thuesday, 3 Aprir 2023 19:40:04',
        content: 'Los elefantes son una de las criaturas más majestuosas y fascinantes que podemos encontrar en la naturaleza. Con su imponente presencia y su inteligencia notable, estos animales nos sorprenden con su capacidad para crear vínculos emocionales y su increíble memoria. Con su piel gruesa y arrugada, los elefantes pueden parecer robustos e imponentes, pero también tienen una gran sensibilidad. Estos animales son capaces de mostrar empatía y compasión hacia los miembros de su manada, y cuidan y protegen a sus crías con una dedicación sin igual. Aunque los elefantes son animales pacíficos, también son capaces de defenderse con gran fuerza y agilidad si sienten que están siendo amenazados. Gracias a su tamaño y fuerza, los elefantes pueden causar un gran impacto en su entorno, desde la creación de senderos a través de la selva hasta la eliminación de árboles y la formación de nuevos cuerpos de agua. Sin embargo, a pesar de su importancia en el ecosistema y su valor como animales increíblemente inteligentes y emocionales, los elefantes han sido objeto de caza y explotación durante siglos. Desde la caza por marfil hasta su uso en circos y espectáculos, estos animales han sufrido mucho a lo largo de la historia. Es por eso que es importante que sigamos trabajando para proteger a los elefantes y preservar su hábitat natural. La conservación de los elefantes y su entorno no solo ayuda a asegurar la supervivencia de esta especie increíble, sino que también ayuda a proteger nuestro planeta y la diversidad de la vida que lo habita. En conclusión, los elefantes son animales fascinantes y notables que merecen ser protegidos y respetados. A través de la educación y la conservación, podemos asegurarnos de que estos animales sigan siendo una parte importante de nuestro mundo natural y que sus increíbles habilidades y emociones continúen inspirándonos por generaciones venideras.',
        tags: ['historias']
    },
    {
        id: 5,
        link: 'evolucin-de-la-agricultura',
        image: 'https://cdn.pixabay.com/photo/2019/05/17/04/58/agriculture-4208863_1280.jpg',
        title: 'La evolución de la agricultura',
        date: 'Thuesday, 3 Aprir 2023 19:40:04',
        content: 'La agricultura ha sido una de las actividades humanas más importantes a lo largo de la historia. Desde la revolución agrícola del Neolítico hasta la agricultura moderna y tecnológica de hoy en día, la producción de alimentos ha evolucionado de manera constante para satisfacer las necesidades cambiantes de la sociedad. En el pasado, la agricultura se basaba en la recolección y cultivo de plantas silvestres y la domesticación de animales para su uso como herramientas y fuentes de alimento. Con el tiempo, la selección y el cultivo selectivo de plantas y la cría selectiva de animales llevaron al desarrollo de cultivos y animales específicos para satisfacer las necesidades de las sociedades agrícolas. La revolución agrícola del Neolítico marcó un cambio significativo en la agricultura, con la introducción de herramientas de piedra y metal, técnicas de irrigación y la construcción de asentamientos agrícolas permanentes. Esto permitió la producción de grandes cantidades de alimentos, lo que permitió el crecimiento de las poblaciones humanas y la formación de ciudades y civilizaciones. Con la llegada de la Revolución Industrial, la agricultura dio un salto gigantesco. La introducción de máquinas agrícolas y técnicas modernas de producción permitió una mayor producción de alimentos y una mayor eficiencia en los procesos de cultivo y cosecha. La agricultura también se volvió más especializada, con agricultores que se centraban en la producción de un tipo específico de cultivo o animal para maximizar la eficiencia. En la actualidad, la agricultura ha alcanzado un nivel sin precedentes de tecnología y eficiencia. La ingeniería genética, la biotecnología y la agricultura de precisión han permitido un aumento en la producción de alimentos y una mejora en la calidad de los cultivos y animales producidos. Además, los métodos agrícolas sostenibles y respetuosos con el medio ambiente se han convertido en una prioridad en la industria, asegurando que la producción de alimentos no dañe el medio ambiente y sea sostenible a largo plazo. En conclusión, la agricultura ha evolucionado significativamente a lo largo de la historia, pasando de técnicas simples de recolección y domesticación de animales a la agricultura moderna y tecnológica. Aunque la producción de alimentos se ha vuelto más eficiente y especializada, la sostenibilidad y el respeto al medio ambiente son cada vez más importantes para garantizar un futuro sostenible para la producción de alimentos y la preservación de nuestro planeta.',
        tags: ['historias']
    },
    {
        id: 6,
        link: 'evolucin-de-la-agricultura',
        image: 'https://cdn.pixabay.com/photo/2019/05/17/04/58/agriculture-4208863_1280.jpg',
        title: 'La evolución de la agricultura',
        date: 'Thuesday, 3 Aprir 2023 19:40:04',
        content: 'La agricultura ha sido una de las actividades humanas más importantes a lo largo de la historia. Desde la revolución agrícola del Neolítico hasta la agricultura moderna y tecnológica de hoy en día, la producción de alimentos ha evolucionado de manera constante para satisfacer las necesidades cambiantes de la sociedad. En el pasado, la agricultura se basaba en la recolección y cultivo de plantas silvestres y la domesticación de animales para su uso como herramientas y fuentes de alimento. Con el tiempo, la selección y el cultivo selectivo de plantas y la cría selectiva de animales llevaron al desarrollo de cultivos y animales específicos para satisfacer las necesidades de las sociedades agrícolas. La revolución agrícola del Neolítico marcó un cambio significativo en la agricultura, con la introducción de herramientas de piedra y metal, técnicas de irrigación y la construcción de asentamientos agrícolas permanentes. Esto permitió la producción de grandes cantidades de alimentos, lo que permitió el crecimiento de las poblaciones humanas y la formación de ciudades y civilizaciones. Con la llegada de la Revolución Industrial, la agricultura dio un salto gigantesco. La introducción de máquinas agrícolas y técnicas modernas de producción permitió una mayor producción de alimentos y una mayor eficiencia en los procesos de cultivo y cosecha. La agricultura también se volvió más especializada, con agricultores que se centraban en la producción de un tipo específico de cultivo o animal para maximizar la eficiencia. En la actualidad, la agricultura ha alcanzado un nivel sin precedentes de tecnología y eficiencia. La ingeniería genética, la biotecnología y la agricultura de precisión han permitido un aumento en la producción de alimentos y una mejora en la calidad de los cultivos y animales producidos. Además, los métodos agrícolas sostenibles y respetuosos con el medio ambiente se han convertido en una prioridad en la industria, asegurando que la producción de alimentos no dañe el medio ambiente y sea sostenible a largo plazo. En conclusión, la agricultura ha evolucionado significativamente a lo largo de la historia, pasando de técnicas simples de recolección y domesticación de animales a la agricultura moderna y tecnológica. Aunque la producción de alimentos se ha vuelto más eficiente y especializada, la sostenibilidad y el respeto al medio ambiente son cada vez más importantes para garantizar un futuro sostenible para la producción de alimentos y la preservación de nuestro planeta.',
        tags: ['historias']
    }
];

export {blogApi};